## security-plugin 相关配置
security:
  server:
    ### security.server.name ,调用security的服务名称
    name: buukle-security
    ### security.server.appResourceURI ,调用security的服务appResource资源的URI

  ### security.openAuth 是否开启认证 : 1,开启 (默认不开启)
  openAuth: 1
  ### security.openPerm 是否开启授权 : 1,开启 (默认不开启)
  openPerm: 1
  ### security.openIsol 是否开启数据隔离 : 1,开启 (默认不开启)
  openIsol: 1
  ### security.openRegs 是否开启接口注册 : 1,开启 (默认不开启)
  openRegs: 0
  passport:
    ### security.passport.host 登机牌中心host配置 "?" 之前是跳转认证失败后跳转的登录中心, 之后是完成登陆后的回跳url
    host: http://tpassport.buukle.top:8080/static/login.html?returnUrl=http://twjs.buukle.top:8080/wjs/home
